# Generated by Django 6.0.4 on 2026-04-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_add_quiz_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obraz_id', models.CharField(max_length=50, unique=True)),
                ('skus', models.CharField(max_length=500)),
                ('obraz_ids_all', models.CharField(blank=True, max_length=500)),
                ('suitable_figure', models.CharField(blank=True, max_length=200)),
                ('suitable_color', models.CharField(blank=True, max_length=200)),
                ('suitable_kibbe', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('silhouette', models.CharField(blank=True, max_length=50)),
                ('suitable_figure', models.CharField(blank=True, max_length=200)),
                ('suitable_color', models.CharField(blank=True, max_length=200)),
                ('suitable_kibbe', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quiz.look')),
            ],
        ),
    ]
