# Generated by Django 6.0.4 on 2026-05-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='products_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
