# Generated by Django 6.0.4 on 2026-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='color_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='figure_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='kibbe_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
