# Generated by Django 6.0.4 on 2026-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_color_type_chatsession_figure_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='gigachat_thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
