# Generated by Django 6.0.4 on 2026-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatsession_gigachat_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='quiz_products',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
