# Generated by Django 6.0.4 on 2026-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatsession_quiz_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='quiz_shown',
            field=models.BooleanField(default=False),
        ),
    ]
